module.exports = {
  config: {
  name: 'quote',
  version: 1.0,
  role: 0,
  author: "Rizky Z (Hadi)", 
  countDown: 20,
  description: "𝗄𝖺𝗍𝖺 𝗄𝖺𝗍𝖺 𝗆𝗎𝗍𝗂𝖺𝗋𝖺", 
  category: 'MEDIA',
  guide: { id: '{pn}' }
},

    onStart: async function({ api, event, message }) {
    const raffa = [
"Janganlah kamu bersikap lemah, Janganlah kamu bersedih hati, dan kamu akan beruntung jika kamu beriman", 
"Sesungguhnya Allah bersama orang-orang yang sabar", 
"Sesungguhnya setiap amal itu tergantung pada niatnya", 
"Kebahagiaan bukan milik orang yang memiliki segalanya, tetapi milik orang yang mensyukuri segala yang dimilikinya", 
"Tuhan tidak akan memberikan beban kepada seseorang melampaui batas kemampuannya", 
"Hidup ini adalah ujian, maka jagalah hatimu agar selalu meraih keberkahan", 
"Kegagalan adalah kesempatan yang Tuhan berikan untuk memperbaiki diri dan bersikap lebih baik", 
"Jika kau ingin mencintai Allah, maka pertama-tama cintailah sesama manusia", 
"Tiada yang tersembunyi bagi Allah di langit dan di bumi", 
"Karena dalam kesulitan, Allah selalu memberikan jalan keluar",
"Ketika hatimu terluka, ingatlah bahwa Allah Maha Penyembuh", 
"Hidup ini singkat, maka manfaatkanlah setiap detiknya untuk berbuat kebaikan", 
"Sesungguhnya kebaikan dan keburukan tidak akan sama", 
"Jangan menyerah, karena di balik kesulitan pasti ada kemudahan",
"Kebaikan adalah investasi terbaik yang bisa kita lakukan untuk hari esok", 
"Ketika doamu belum terjawab, ingatlah bahwa Allah selalu hadir dan mendengar", 
"Ketulusan hati adalah kunci utama kebahagiaan sejati", 
"Jangan menyia-nyiakan waktu, karena waktu adalah salah satu nikmat terbesar dari Allah", 
"Sesungguhnya setiap langkah kebaikan yang kita lakukan akan membuahkan hasil di waktu yang tepat", 
"Perlakukan orang lain sebagaimana kamu ingin diperlakukan", 
"Ketika hatimu penuh dengan ketakutan, percayalah bahwa Allah selalu memberikan perlindungan", 
"Ketika kehidupan terasa sulit, ingatlah bahwa Allah Maha Mengarahkan", 
"Doa adalah senjata yang paling ampuh bagi orang beriman", 
"Jangan pernah lelah berbuat kebaikan, karena setiap amal baik pasti akan mendatangkan kebaikan", 
"Ingatlah bahwa rejeki yang telah ditetapkan Allah untukmu tidak akan pernah tertukar dengan rejeki orang lain", 
"Belajarlah dari kesalahan, karena kesalahan adalah guru terbaik dalam hidup", 
"Ketika menghadapi cobaan, bersabarlah, karena di situlah letak kekuatanmu", 
"Jangan pernah putus asa, karena di balik awan gelap pasti ada sinar mentari yang bersinar", 
"Petunjuk hidup ada dalam petunjuk Allah yang tertuang dalam Al-Quran", 
"Percayalah bahwa setiap kesulitan pasti akan berakhir dengan kebahagiaan", 
"Jangan sia-siakan kesempatan yang Tuhan berikan untuk berbuat kebaikan", 
"Ketika hatimu terasa hampa, ingatlah bahwa Allah selalu mendengar doamu", 
"Ketulusan niat dalam beribadah adalah kunci utama diterimanya amal", 
"Tidak ada kehidupan yang sia-sia di sisi Allah", 
"Ketika kehidupan terasa pahit, ingatlah bahwa Allah selalu memberikan kelezatan di tengah-tengah pahitnya", 
"Jangan pernah takut untuk bertindak di jalan kebenaran, karena Tuhan selalu menolong orang-orang yang ikhlas", 
"Ketika dunia terasa gelap, percayalah bahwa Allah adalah sumber terang kehidupan", 
"Jangan pernah mengeluh, karena setiap ujian adalah bentuk cinta dari Allah yang ingin mempersiapkanmu menjadi lebih baik", 
"Kesederhanaan adalah kunci kebahagiaan yang abadi", 
"Ketika hatimu dipenuhi oleh kesedihan, ingatlah bahwa Allah selalu hadir untuk menghiburmu", 
"Jangan pernah merasa sendiri, karena Allah selalu dekat denganmu", 
"Ketika kehidupan terasa penuh dengan rintangan, percayalah bahwa Allah selalu memberikan jalan keluar", 
"Masa lalu adalah pembelajaran, masa kini adalah amal, dan masa depan adalah harapan", 
"Hidup adalah perjuangan, maka berjuanglah dengan penuh keyakinan kepada Allah", 
"Ketika hatimu dipenuhi oleh kebencian, ingatlah bahwa Allah adalah sumber cinta sejati", 
"Jangan pernah menyesali masa lalu, karena semua telah diatur oleh Allah dengan sebaik-baiknya", 
"Kesabaran adalah kunci kesuksesan yang sejati", 
"Ketika kehidupan terasa menyakitkan, percayalah bahwa Allah selalu melihatmu dengan penuh kasih sayang", 
"Jangan pernah menyerah, karena Tuhan tidak pernah menyerah kepada hamba-Nya yang taat", 
"Ketika hatimu terasa hampa, ingatlah bahwa Allah adalah sumber kebahagiaan yang sejati", 
"Sesungguhnya setiap individu bertanggung jawab atas amal perbuatannya sendiri", 
"Ketika kehidupan terasa sulit, percayalah bahwa Allah selalu memberikan bantuan melalui jalan yang tidak terduga", 
"Keikhlasan adalah kunci keselamatan di akhirat", 
"Jangan pernah mengeluh, karena setiap ujian adalah ujian yang Tuhan berikan untuk menguatkan imanmu", 
"Ketika hatimu penuh dengan kegelapan, ingatlah bahwa Allah adalah sumber terang yang tak pernah padam", 
"Jangan pernah merasa sendiri, karena Allah selalu menemanimu di setiap langkah kehidupan", 
"Ketika kehidupan terasa penuh dengan rintangan, percayalah bahwa Allah selalu memberikan kemudahan di setiap langkahmu", 
"Kesetiaan dalam beribadah adalah kunci keberhasilan dalam meraih keberkahan hidup", 
"Jangan sia-siakan waktu, karena setiap detiknya adalah anugerah yang Allah berikan untukmu", 
"Ketika hatimu dipenuhi oleh keraguan, ingatlah bahwa Allah adalah sumber kebenaran yang abadi"
];
    const hadi = raffa[Math.floor(Math.random() * raffa.length)];
    message.reply(`✨ 𝗤𝘂𝗼𝘁𝗲\n\n${hadi}`);
 }
};